# Generated by Django 3.2 on 2022-04-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
