# Generated by Django 3.2 on 2022-04-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_reviews_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
